name: my_flutter_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

# Application versioning
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  image_picker: ^1.1.2
  intl_phone_field: ^3.1.0
  intl: ^0.20.2
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/homebg.jpeg  # Correctly placed asset path
    - assets/images/ut.webp  # Correctly placed asset path
    - assets/images/ud.jpeg  # Correctly placed asset path
    - assets/images/udweb.jpg  # Correctly placed asset path
    - assets/images/ad.jpeg  # Correctly placed asset path
    - assets/images/adweb.jpeg  # Correctly placed asset path
    - assets/images/homebgweb.jpeg  # Correctly placed asset path

